// <auto-generated />
namespace Gigs1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAttendnce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAttendnce));
        
        string IMigrationMetadata.Id
        {
            get { return "201705172146042_AddAttendnce"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
